name: skeleton
recipe: laravel
config:
  php: "8.1"
  composer_version: 2
  via: nginx
  webroot: public
  database: mariadb
  cache: none
  xdebug: false
services:
  database:
    type: mariadb:10.6
    portforward: true
    creds:
      user: web
      password: ""
      database: skeleton
  database_testing:
    type: mariadb:10.6
    portforward: true
    creds:
      user: web
      password: ""
      database: skeleton
  appserver:
    type: php:8.1
    run_as_root:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - npm install --global yarn
    build:
      - composer install
tooling:
  phpstan:
    service: appserver
    cmd: /app/vendor/bin/phpstan
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/php-cs-fixer
  npm:
    service: appserver
    cmd: npm
  yarn:
    service: appserver
    cmd: yarn
  ci:
    service: appserver
    cmd: |
      php artisan migrate
      php artisan model-doc:generate
      /app/vendor/bin/php-cs-fixer fix
      /app/vendor/bin/phpstan
      /app/vendor/bin/phpunit
  ci-fresh:
    service: appserver
    cmd: |
      php artisan migrate:fresh --seed
      php artisan model-doc:generate
      /app/vendor/bin/php-cs-fixer fix
      /app/vendor/bin/phpstan
      /app/vendor/bin/phpunit
