version: "3.9"

services:
  web:
    restart: unless-stopped
    env_file:
      - ./web/.env
    build:
      context: $LOCAL_PROJECT_PATH
      dockerfile: .docker/web/Dockerfile
      args:
        NOVA_USERNAME: $NOVA_USERNAME
        NOVA_LICENSE_KEY: $NOVA_LICENSE_KEY
    volumes:
      - ./web/app.conf:/etc/nginx/conf.d/app.conf
      - ./web/.env:/app/.env
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
    ports:
      - "8000:80"
    networks:
      - app-network

  queue:
    command: ["sh", "run/queue.sh"]
    restart: unless-stopped
    env_file:
      - ./web/.env
    build:
      context: $LOCAL_PROJECT_PATH
      dockerfile: .docker/queue/Dockerfile
      args:
        NOVA_USERNAME: $NOVA_USERNAME
        NOVA_LICENSE_KEY: $NOVA_LICENSE_KEY
    environment:
      QUEUE: default
    volumes:
      - ./web/.env:/app/.env
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
    networks:
      - app-network
    depends_on:
      - database

  scheduler:
    command: ["sh", "run/scheduler.sh"]
    restart: unless-stopped
    env_file:
      - ./web/.env
    build:
      context: $LOCAL_PROJECT_PATH
      dockerfile: .docker/scheduler/Dockerfile
      args:
        NOVA_USERNAME: $NOVA_USERNAME
        NOVA_LICENSE_KEY: $NOVA_LICENSE_KEY
    volumes:
      - ./web/.env:/app/.env
      - ./storage/app:/app/storage/app
      - ./storage/logs:/app/storage/logs
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "8001:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MARIADB_ROOT_HOST: "%"
      MARIADB_DATABASE: $DB_DATABASE
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-volume:
