name: "Deploy"

on: [ workflow_dispatch ]

jobs:
  build:
    name: Build
    uses: PietSmietde/Actions/.github/workflows/docker-build-push.yml@main
    strategy:
      matrix:
        target: [ web, cli ]
    with:
      environment: development
      repository: streamfinity/${{ matrix.target }}
      dockerfile: .docker/${{ matrix.target }}/Dockerfile
    secrets:
      docker-build-args: |
        NOVA_USERNAME=${{ secrets.NOVA_USERNAME }}
        NOVA_PASSWORD=${{ secrets.NOVA_PASSWORD }}
        NPM_TOKEN=${{ secrets.NPM_TOKEN }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
