name: Deploy

on: [ workflow_dispatch ]

env:
  ENVIRONMENT: production

jobs:
  build:
    name: "Build ${{ matrix.role }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [ web, queue, scheduler ]
    env:
      REPOSITORY: skeleton

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}/${{ matrix.role }}
          tags: |
            type=raw,value=${{ matrix.role }},prefix=env-
            type=ref,event=branch,prefix=branch-
            type=ref,event=pr,prefix=pr-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          github-token: ${{ github.token }}

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ".docker/${{ matrix.role }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
