name: PHP-CS-Fixer

on: [push]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        composer-dependency: [prefer-stable]

    name: "Run PHP-CS-Fixer"

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --${{ matrix.composer-dependency }}

      - name: Execute PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
