name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "PHP ${{ matrix.php }} - ${{ matrix.composer-prefer }}"
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0 ]
        composer-prefer: [ stable ]
    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --no-interaction --no-scripts --no-progress --prefer-dist --prefer-${{ matrix.composer-prefer }}

      - name: Generate app key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Execute tests
        run: vendor/bin/phpunit
